name: WordPress Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Deploy WordPress
        run: |
          rsync -r --delete-after --quiet $GITHUB_WORKSPACE/ ujeb@3.110.119.180:/var/www/html/wordpress
