name: WordPress Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get install -y rsync
          chmod 600 ~/.ssh/id_rsa
          

      - name: Deploy WordPress
        run: |
          rsync -rav --delete-after --quiet -e "ssh -i ~/.ssh/id_rsa" $GITHUB_WORKSPACE/ ujeb@3.110.119.180:/home/ujeb/wordpress/
          ssh ujeb@3.110.119.180 "sudo cp -r /home/ujeb/wordpress/* /var/www/html/wordpress"
          ssh ujeb@3.110.119.180 "sudo chown -R www-data:www-data /var/www/html/wordpress"
          sudo ssh ujeb@3.110.119.180 "sudo chown -R 755 /var/www/html/wordpress"
          ssh ujeb@3.110.119.180 "sudo systemctl restart nginx php8.1-fpm"
          
